import { DailyStat, PrAction, MonitoredRepo, JulesSession, TriggerRun } from './types';

export interface DashboardData {
  stats: DailyStat[];
  actions: PrAction[];
  repos: MonitoredRepo[];
  sessions: JulesSession[];
  triggerRuns: TriggerRun[];
  totalMerged: number;
  totalClosed: number;
  generatedAt: string | null;
}

// Auto-generated — do not edit manually.
// Regenerated by the dashboard_data subagent.
export const dashboardData: DashboardData = {
  "stats": [
    {
      "date": "2026-05-13",
      "prs_merged": 2,
      "prs_closed": 16,
      "sessions_created": 0,
      "sessions_completed": 0,
      "repos_cleared": 0
    },
    {
      "date": "2026-04-27",
      "prs_merged": 5,
      "prs_closed": 30,
      "sessions_created": 0,
      "sessions_completed": 0,
      "repos_cleared": 0
    },
    {
      "date": "2026-04-16",
      "prs_merged": 1,
      "prs_closed": 28,
      "sessions_created": 0,
      "sessions_completed": 0,
      "repos_cleared": 0
    },
    {
      "date": "2026-04-08",
      "prs_merged": 6,
      "prs_closed": 33,
      "sessions_created": 0,
      "sessions_completed": 0,
      "repos_cleared": 0
    },
    {
      "date": "2026-03-31",
      "prs_merged": 10,
      "prs_closed": 6,
      "sessions_created": 0,
      "sessions_completed": 0,
      "repos_cleared": 2
    },
    {
      "date": "2026-03-18",
      "prs_merged": 6,
      "prs_closed": 34,
      "sessions_created": 0,
      "sessions_completed": 0,
      "repos_cleared": 0
    },
    {
      "date": "2026-03-12",
      "prs_merged": 6,
      "prs_closed": 34,
      "sessions_created": 0,
      "sessions_completed": 0,
      "repos_cleared": 0
    }
  ],
  "actions": [
    {
      "id": 168,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 281,
      "action": "closed",
      "title": "🎨 Palette: [UX improvement] Improve chat interface accessibility",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 169,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 285,
      "action": "closed",
      "title": "🛡️ Sentinel: [CRITICAL] Fix authorization bypass in client bundle",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 170,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 288,
      "action": "closed",
      "title": "🛡️ Sentinel: [HIGH] Fix predictable authorization bypass",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 171,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 290,
      "action": "closed",
      "title": "🛡️ Sentinel: [MEDIUM] Update dependencies to fix security vulnerabilities",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 172,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 291,
      "action": "closed",
      "title": "🎨 Palette: Improve chat accessibility with screen reader enhancements",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 173,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 294,
      "action": "closed",
      "title": "🛡️ Sentinel: [MEDIUM] Fix information leakage in error logs",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 174,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 295,
      "action": "closed",
      "title": "⚡ Bolt: Code split NotaryAssistant chat window",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 175,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 296,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement] Mitigate automated brute-force on admin login",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 176,
      "repo": "electron",
      "pr_number": 400,
      "action": "closed",
      "title": "🎨 Palette: Improve accessibility of icon-only buttons in PolaroidMemory",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 177,
      "repo": "Naming-Nosferatu",
      "pr_number": 846,
      "action": "closed",
      "title": "🧹 chore: remove stray console.log from TournamentFlow",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 178,
      "repo": "Naming-Nosferatu",
      "pr_number": 847,
      "action": "closed",
      "title": "🧪 Add tests for parseJsonValue in storage.ts",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 179,
      "repo": "Naming-Nosferatu",
      "pr_number": 848,
      "action": "closed",
      "title": "chore: remove informational logs from tournament handlers and flow",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 180,
      "repo": "Naming-Nosferatu",
      "pr_number": 849,
      "action": "closed",
      "title": "fix: DOM-based XSS via Unescaped innerHTML in deployment overlay",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 181,
      "repo": "Naming-Nosferatu",
      "pr_number": 853,
      "action": "closed",
      "title": "security: replace hardcoded password with environment variable",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 182,
      "repo": "Naming-Nosferatu",
      "pr_number": 854,
      "action": "closed",
      "title": "fix: remove leftover console logs in TournamentFlow",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 183,
      "repo": "Naming-Nosferatu",
      "pr_number": 856,
      "action": "closed",
      "title": "perf(websocket): optimize callback management with Set",
      "reason": "conflict",
      "created_at": "2026-05-13 17:30:03"
    },
    {
      "id": 167,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 283,
      "action": "merged",
      "title": "⚡ Bolt: Hardware Accelerated Scroll Progress",
      "reason": "clean_merge",
      "created_at": "2026-05-12 00:02:39"
    },
    {
      "id": 166,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 292,
      "action": "merged",
      "title": "🛡️ Sentinel: [CRITICAL/HIGH] Fix XSS vulnerability",
      "reason": "clean_merge",
      "created_at": "2026-05-08 19:58:57"
    },
    {
      "id": 165,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 282,
      "action": "merged",
      "title": "🛡️ Sentinel: [HIGH] Fix Authorization Bypass",
      "reason": "clean_merge",
      "created_at": "2026-05-01 17:48:56"
    },
    {
      "id": 133,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 271,
      "action": "merged",
      "title": "⚡ Bolt: [performance improvement] Preload LCP hero image",
      "reason": "clean_merge",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 134,
      "repo": "zine-ify",
      "pr_number": 253,
      "action": "merged",
      "title": "🎨 Palette: Add aria-label to icon-only buttons in Template",
      "reason": "clean_merge",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 135,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 276,
      "action": "closed",
      "title": "🎨 Palette: [UX improvement] Enhance Chat Accessibility",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 136,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 275,
      "action": "closed",
      "title": "⚡ Bolt: [performance improvement] Code-split hidden ChatWindow component",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 137,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 274,
      "action": "closed",
      "title": "🎨 Palette: [Chat Accessibility UX improvements]",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 138,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 273,
      "action": "closed",
      "title": "🎨 Palette: [UX improvement] Add aria-expanded and aria-controls to chat toggle button",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 139,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 272,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement] Prevent information exposure via error logs",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 140,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 270,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement] Prevent information leakage via raw error objects in console methods",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 141,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 269,
      "action": "closed",
      "title": "⚡ Bolt: Preload critical hero image for LCP optimization",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 142,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 268,
      "action": "closed",
      "title": "🎨 Palette: Add accessibility attributes to chat toggle",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 143,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 267,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement] Remove unsafe-eval from CSP",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 144,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 266,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement] Add admin session timeout",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 145,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 265,
      "action": "closed",
      "title": "⚡ Bolt: [performance improvement] Code split NotaryAssistant chat window",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 146,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 264,
      "action": "closed",
      "title": "🛡️ Sentinel: [HIGH] Fix vulnerable react-router dependencies",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 147,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 263,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement] Prevent information exposure via console error logs",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 148,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 262,
      "action": "closed",
      "title": "🎨 Palette: Add screen reader context to chat messages",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 149,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 261,
      "action": "closed",
      "title": "⚡ Bolt: [performance improvement] Preload critical hero image for LCP optimization",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 150,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 259,
      "action": "closed",
      "title": "🎨 Palette: [UX improvement] Enhance chat interface accessibility",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 151,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 258,
      "action": "closed",
      "title": "⚡ Bolt: [performance improvement] Preload hero image to optimize LCP",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 152,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 257,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement]",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 153,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 256,
      "action": "closed",
      "title": "🎨 Palette: Add ARIA label to hidden file input",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 154,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 255,
      "action": "closed",
      "title": "⚡ Bolt: Preload critical hero image for faster LCP",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 155,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 253,
      "action": "closed",
      "title": "🎨 Palette: [UX improvement] Enhance floating chat accessibility",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 156,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 251,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement]",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 157,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 250,
      "action": "closed",
      "title": "⚡ Bolt: Preload critical hero image",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 158,
      "repo": "zine-ify",
      "pr_number": 258,
      "action": "closed",
      "title": "🎨 Palette: Improve keyboard focus accessibility and icon button labels",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 159,
      "repo": "zine-ify",
      "pr_number": 257,
      "action": "closed",
      "title": "⚡ Bolt: Optimize PDF thumbnail generation concurrency",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 160,
      "repo": "zine-ify",
      "pr_number": 255,
      "action": "closed",
      "title": "🛡️ Sentinel: [MEDIUM] Prevent Error Data Exposure by sanitizing console.error",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 161,
      "repo": "zine-ify",
      "pr_number": 254,
      "action": "closed",
      "title": "⚡ Bolt: [performance improvement] concurrent PDF rendering",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 162,
      "repo": "zine-ify",
      "pr_number": 249,
      "action": "closed",
      "title": "🛡️ Sentinel: [MEDIUM] Enhance CSP with object-src and base-uri restrictions",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 163,
      "repo": "zine-ify",
      "pr_number": 248,
      "action": "closed",
      "title": "🛡️ Sentinel: [Enhancement] Add CSP to dynamic print window",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 164,
      "repo": "zine-ify",
      "pr_number": 247,
      "action": "closed",
      "title": "🛡️ Sentinel: [HIGH] Fix Client-Side DoS via Unbounded Cumulative PDF Pages",
      "reason": "conflict",
      "created_at": "2026-04-27 15:40:39"
    },
    {
      "id": 131,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 278,
      "action": "merged",
      "title": "🛡️ Sentinel: [security improvement] Prevent error object leakage in console",
      "reason": "clean_merge",
      "created_at": "2026-04-20 16:44:59"
    },
    {
      "id": 132,
      "repo": "zine-ify",
      "pr_number": 259,
      "action": "merged",
      "title": "🛡️ Sentinel: [Medium] Fix Error Data Exposure",
      "reason": "clean_merge",
      "created_at": "2026-04-20 16:44:59"
    },
    {
      "id": 122,
      "repo": "zine-ify",
      "pr_number": 246,
      "action": "closed",
      "title": "⚡ Bolt: Improve PDF processing performance with sliding window concurrency",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 123,
      "repo": "zine-ify",
      "pr_number": 245,
      "action": "closed",
      "title": "🛡️ Sentinel: [MEDIUM] Fix Error Data Exposure",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 124,
      "repo": "electron",
      "pr_number": 379,
      "action": "closed",
      "title": "🧪 Add tests for movieRecords normalization",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 125,
      "repo": "electron",
      "pr_number": 377,
      "action": "closed",
      "title": "⚡ Batch movie memory updates on rename (N+1 fix)",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 126,
      "repo": "electron",
      "pr_number": 376,
      "action": "closed",
      "title": "🧪 Add unit tests for layouts utility",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 127,
      "repo": "electron",
      "pr_number": 375,
      "action": "closed",
      "title": "⚡ Optimize array traversal in SpinWheelGame render",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 128,
      "repo": "electron",
      "pr_number": 374,
      "action": "closed",
      "title": "🧪 Add tests for validateMemory",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 129,
      "repo": "electron",
      "pr_number": 372,
      "action": "closed",
      "title": "🧪 Add tests for shuffleArray in random.ts",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 130,
      "repo": "electron",
      "pr_number": 371,
      "action": "closed",
      "title": "[ImgBot] Optimize images",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:06"
    },
    {
      "id": 102,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 254,
      "action": "merged",
      "title": "🛡️ Sentinel [HIGH] Fix Arbitrary File Read in Vite",
      "reason": "clean_merge",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 103,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 252,
      "action": "closed",
      "title": "⚡ Bolt Preload critical hero image for LCP",
      "reason": "conflict",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 104,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 249,
      "action": "closed",
      "title": "🎨 Palette: Add aria-expanded and aria-controls to chat toggle button",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 105,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 248,
      "action": "closed",
      "title": "⚡ Bolt: Preload critical hero image for faster LCP",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 106,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 247,
      "action": "closed",
      "title": "🎨 Palette: Improve Chat Assistant Accessibility",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 107,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 246,
      "action": "closed",
      "title": "🛡️ Sentinel: [security improvement]",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 108,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 245,
      "action": "closed",
      "title": "🎨 Palette: [UX improvement] Add focus visible styles to Admin input",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 109,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 244,
      "action": "closed",
      "title": "⚡ Bolt: [performance improvement] Preload LCP Image in HTML",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 110,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 243,
      "action": "closed",
      "title": "🛡️ Sentinel: [HIGH] Fix Vite Arbitrary File Read vulnerability",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 111,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 242,
      "action": "closed",
      "title": "⚡ Bolt: [performance improvement] Preload LCP Hero image",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 112,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 241,
      "action": "closed",
      "title": "🛡️ Sentinel: [HIGH] Fix Arbitrary File Read and Path Traversal in Vite",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 113,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 240,
      "action": "closed",
      "title": "🎨 Palette: Add tooltip to sticky call button",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 114,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 238,
      "action": "closed",
      "title": "🎨 Palette: Add click-outside-to-dismiss for ImageCropper modal",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 115,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 237,
      "action": "closed",
      "title": "⚡ Bolt: Prevent O(N) re-renders in chat messages",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 116,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 236,
      "action": "closed",
      "title": "🛡️ Sentinel: [CRITICAL/HIGH] Fix Content-Security-Policy unsafe-eval",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 117,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 235,
      "action": "closed",
      "title": "⚡ Bolt: Prevent O(N) re-renders in NotaryAssistant",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 118,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 234,
      "action": "closed",
      "title": "🛡️ Sentinel: [HIGH] Fix unsafe-eval in Content Security Policy",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 119,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 233,
      "action": "closed",
      "title": "⚡ Bolt: Memoize ChatMessageItem to prevent O(N) re-renders",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 120,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 232,
      "action": "closed",
      "title": "🛡️ Sentinel: [CRITICAL] Remove unsafe-eval from CSP",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 121,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 231,
      "action": "closed",
      "title": "🎨 Palette: Add loading state to admin login",
      "reason": "stale_base",
      "created_at": "2026-04-16 16:51:02"
    },
    {
      "id": 87,
      "repo": "zine-ify",
      "pr_number": 212,
      "action": "closed",
      "title": "🛡️ [HIGH] Fix client-side DoS in file upload",
      "reason": "duplicate",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 88,
      "repo": "zine-ify",
      "pr_number": 210,
      "action": "closed",
      "title": "⚡ OffscreenCanvas for background rendering",
      "reason": "duplicate",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 89,
      "repo": "zine-ify",
      "pr_number": 208,
      "action": "closed",
      "title": "⚡ OffscreenCanvas background rendering",
      "reason": "duplicate",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 90,
      "repo": "zine-ify",
      "pr_number": 207,
      "action": "closed",
      "title": "⚡ OffscreenCanvas background PDF rendering",
      "reason": "duplicate",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 91,
      "repo": "zine-ify",
      "pr_number": 202,
      "action": "closed",
      "title": "🛡️ Enhance CSP",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 92,
      "repo": "zine-ify",
      "pr_number": 201,
      "action": "closed",
      "title": "⚡ Cache DOM queries",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 93,
      "repo": "zine-ify",
      "pr_number": 200,
      "action": "closed",
      "title": "🎨 Make progress overlay accessible",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 94,
      "repo": "zine-ify",
      "pr_number": 162,
      "action": "closed",
      "title": "🛡️ [HIGH] Fix DoS massive DOM node creation",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 95,
      "repo": "zine-ify",
      "pr_number": 159,
      "action": "closed",
      "title": "🎨 ARIA labels icon-only toolbar",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 96,
      "repo": "zine-ify",
      "pr_number": 157,
      "action": "closed",
      "title": "⚡ Optimize DOM creation",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 97,
      "repo": "zine-ify",
      "pr_number": 155,
      "action": "closed",
      "title": "🎨 focus states action buttons",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 98,
      "repo": "zine-ify",
      "pr_number": 154,
      "action": "closed",
      "title": "⚡ Sliding window concurrency",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 99,
      "repo": "zine-ify",
      "pr_number": 153,
      "action": "closed",
      "title": "🛡️ [HIGH] Fix DOM XSS in uploaded files",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 100,
      "repo": "zine-ify",
      "pr_number": 152,
      "action": "closed",
      "title": "🎨 aria-hidden Material Symbols",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 101,
      "repo": "zine-ify",
      "pr_number": 142,
      "action": "closed",
      "title": "🛡️ [HIGH] Fix DOM-based XSS in Zine UI",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:36"
    },
    {
      "id": 70,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 224,
      "action": "closed",
      "title": "🎨 Improve Chat Accessibility and Tactile Feedback",
      "reason": "conflict",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 71,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 226,
      "action": "closed",
      "title": "🛡️ [HIGH] Fix XSS via unsafe-eval in CSP",
      "reason": "duplicate",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 72,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 223,
      "action": "closed",
      "title": "⚡ Extract ChatMessageItem memoization",
      "reason": "duplicate",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 73,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 217,
      "action": "closed",
      "title": "🎨 focus state cropper zoom slider",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 74,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 216,
      "action": "closed",
      "title": "⚡ Extract ChatInput",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 75,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 201,
      "action": "closed",
      "title": "🛡️ [HIGH] Secure admin password",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 76,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 200,
      "action": "closed",
      "title": "🛡️ Add rate limit to Gemini API",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 77,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 188,
      "action": "closed",
      "title": "🎨 focus ring states",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 78,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 187,
      "action": "closed",
      "title": "⚡ Memoize LandingPage",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 79,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 181,
      "action": "closed",
      "title": "🎨 semantic FAQs",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 80,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 167,
      "action": "closed",
      "title": "⚡ Bypass React Render Cycle Scroll",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 81,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 156,
      "action": "closed",
      "title": "🛡️ Add CSP",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 82,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 146,
      "action": "closed",
      "title": "🎨 Replace window.alert",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 83,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 139,
      "action": "closed",
      "title": "⚡ Optimize icon rendering",
      "reason": "stale_base",
      "created_at": "2026-04-08 01:17:27"
    },
    {
      "id": 67,
      "repo": "zine-ify",
      "pr_number": 213,
      "action": "merged",
      "title": "⚡ Bolt: Use OffscreenCanvas for PDF processing",
      "reason": "clean_merge",
      "created_at": "2026-04-07 23:10:00"
    },
    {
      "id": 68,
      "repo": "zine-ify",
      "pr_number": 214,
      "action": "closed",
      "title": "🎨 Palette: Improve keyboard focus styles and modal close button accessibility",
      "reason": "conflict",
      "created_at": "2026-04-07 23:10:00"
    },
    {
      "id": 64,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 225,
      "action": "merged",
      "title": "🎨 Palette: Add focus-visible states to navbar logo button",
      "reason": "clean_merge",
      "created_at": "2026-04-07 23:09:28"
    },
    {
      "id": 65,
      "repo": "zine-ify",
      "pr_number": 216,
      "action": "closed",
      "title": "🎨 Palette: Accessible focus states for form controls",
      "reason": "conflict",
      "created_at": "2026-04-07 23:09:28"
    },
    {
      "id": 66,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 227,
      "action": "closed",
      "title": "⚡ Bolt: Prevent O(N) Re-renders for Chat Messages",
      "reason": "conflict",
      "created_at": "2026-04-07 23:09:28"
    },
    {
      "id": 62,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 228,
      "action": "merged",
      "title": "🎨 Palette: Add keyboard focus-visible states to brand toggle",
      "reason": "clean_merge",
      "created_at": "2026-04-07 23:08:04"
    },
    {
      "id": 63,
      "repo": "zine-ify",
      "pr_number": 217,
      "action": "closed",
      "title": "🎨 Palette: Add loading spinner to async export button",
      "reason": "conflict",
      "created_at": "2026-04-07 23:08:04"
    },
    {
      "id": 61,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 230,
      "action": "merged",
      "title": "⚡ Bolt: [performance improvement] React.memo for ChatMessageItem",
      "reason": "clean_merge",
      "created_at": "2026-04-06 03:55:37"
    },
    {
      "id": 59,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 229,
      "action": "merged",
      "title": "🛡️ Sentinel: [HIGH] Fix unsafe-eval in Content-Security-Policy",
      "reason": "clean_merge",
      "created_at": "2026-04-06 03:55:25"
    },
    {
      "id": 60,
      "repo": "zine-ify",
      "pr_number": 215,
      "action": "merged",
      "title": "🛡️ Sentinel: [HIGH] Fix Client-Side DoS via Unbounded File Uploads",
      "reason": "clean_merge",
      "created_at": "2026-04-06 03:55:25"
    },
    {
      "id": 55,
      "repo": "zine-ify",
      "pr_number": 186,
      "action": "merged",
      "title": "Sentinel: Add Content Security Policy (CSP)",
      "reason": "clean_merge",
      "created_at": "2026-03-30 16:44:42"
    },
    {
      "id": 56,
      "repo": "zine-ify",
      "pr_number": 185,
      "action": "closed",
      "title": "Bolt: Optimize PDF page rendering with sliding window",
      "reason": "conflict",
      "created_at": "2026-03-30 16:44:42"
    },
    {
      "id": 57,
      "repo": "zine-ify",
      "pr_number": 184,
      "action": "closed",
      "title": "Palette: Improve accessibility - aria labels",
      "reason": "conflict",
      "created_at": "2026-03-30 16:44:42"
    },
    {
      "id": 58,
      "repo": "Naming-Nosferatu",
      "pr_number": 766,
      "action": "closed",
      "title": "feat: Add fail-fast DATABASE_URL check",
      "reason": "conflict",
      "created_at": "2026-03-30 16:44:42"
    },
    {
      "id": 53,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 193,
      "action": "merged",
      "title": "Security: Remove hardcoded admin password",
      "reason": "clean_merge",
      "created_at": "2026-03-30 16:44:32"
    },
    {
      "id": 54,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 192,
      "action": "merged",
      "title": "Fix admin authentication security issue",
      "reason": "clean_merge",
      "created_at": "2026-03-30 16:44:32"
    },
    {
      "id": 51,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 205,
      "action": "merged",
      "title": "Sentinel: [security improvement] Add timeout to Gemini API calls",
      "reason": "clean_merge",
      "created_at": "2026-03-30 16:44:23"
    },
    {
      "id": 52,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 206,
      "action": "merged",
      "title": "Bolt: [performance improvement] Optimize Navbar Scroll Listener",
      "reason": "clean_merge",
      "created_at": "2026-03-30 16:44:23"
    },
    {
      "id": 49,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 157,
      "action": "merged",
      "title": "Bolt: direct DOM manipulation for scroll progress",
      "reason": "clean_merge",
      "created_at": "2026-03-12 10:47:08"
    },
    {
      "id": 50,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 117,
      "action": "closed",
      "title": "Palette: Replace native alerts with Toast notifications",
      "reason": "conflict",
      "created_at": "2026-03-12 10:47:08"
    },
    {
      "id": 48,
      "repo": "bledsoe-mobile-notary",
      "pr_number": 159,
      "action": "merged",
      "title": "Sentinel: Add Content Security Policy",
      "reason": "clean_merge",
      "created_at": "2026-03-08 19:55:45"
    },
    {
      "id": 47,
      "repo": "zine-ify",
      "pr_number": 151,
      "action": "merged",
      "title": "Sentinel: Fix DOM XSS in uploaded files list",
      "reason": "clean_merge",
      "created_at": "2026-03-08 19:55:37"
    },
    {
      "id": 30,
      "repo": "zine-ify",
      "pr_number": 122,
      "action": "closed",
      "title": "Sentinel: Harden PDF validation and disable scripting",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 31,
      "repo": "zine-ify",
      "pr_number": 121,
      "action": "closed",
      "title": "Sentinel: Fix loose PDF file validation and disable JS execution",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 32,
      "repo": "zine-ify",
      "pr_number": 120,
      "action": "closed",
      "title": "Bolt: Fix memory leaks and optimize blank page generation",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 33,
      "repo": "zine-ify",
      "pr_number": 119,
      "action": "closed",
      "title": "Palette: Add loading spinner to Export button",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 34,
      "repo": "zine-ify",
      "pr_number": 118,
      "action": "closed",
      "title": "Bolt: Cache blank page blobs to reduce memory usage",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 35,
      "repo": "zine-ify",
      "pr_number": 117,
      "action": "closed",
      "title": "Sentinel: Fix PDF file signature validation vulnerability",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 36,
      "repo": "zine-ify",
      "pr_number": 116,
      "action": "closed",
      "title": "feat(ui): implement keyboard shortcuts and tooltips",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 37,
      "repo": "zine-ify",
      "pr_number": 115,
      "action": "closed",
      "title": "Fix PDF validation and Toast XSS vulnerabilities",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 38,
      "repo": "zine-ify",
      "pr_number": 114,
      "action": "closed",
      "title": "Sentinel: Fix PDF Polyglot Vulnerability",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 39,
      "repo": "zine-ify",
      "pr_number": 113,
      "action": "closed",
      "title": "Palette: Improve accessibility of flip buttons",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 40,
      "repo": "zine-ify",
      "pr_number": 112,
      "action": "closed",
      "title": "Bolt: Optimize PDF processing concurrency and fix memory leaks",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 41,
      "repo": "zine-ify",
      "pr_number": 111,
      "action": "closed",
      "title": "Bolt: Fix memory leak and remove dead code",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 42,
      "repo": "zine-ify",
      "pr_number": 110,
      "action": "closed",
      "title": "Sentinel: Enforce strict PDF signature validation to prevent polyglots",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 43,
      "repo": "zine-ify",
      "pr_number": 109,
      "action": "closed",
      "title": "feat(a11y): improve accessibility of page flip buttons",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 44,
      "repo": "zine-ify",
      "pr_number": 108,
      "action": "closed",
      "title": "Bolt: Cache blank page & fix memory leak",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 45,
      "repo": "zine-ify",
      "pr_number": 107,
      "action": "closed",
      "title": "Sentinel: Add Content Security Policy (CSP)",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 46,
      "repo": "zine-ify",
      "pr_number": 106,
      "action": "closed",
      "title": "Palette: Improved accessibility for flip buttons with dynamic page labels",
      "reason": "conflict",
      "created_at": "2026-03-08 19:54:05"
    },
    {
      "id": 15,
      "repo": "electron",
      "pr_number": 238,
      "action": "closed",
      "title": "Refactor Toast component to optimize object creation",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 16,
      "repo": "electron",
      "pr_number": 234,
      "action": "closed",
      "title": "Remove unreachable ProfileSheet component",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 17,
      "repo": "electron",
      "pr_number": 232,
      "action": "closed",
      "title": "Fix Gemini API key exposure in URL",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 18,
      "repo": "electron",
      "pr_number": 231,
      "action": "closed",
      "title": "Fix hardcoded Supabase credentials",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 19,
      "repo": "electron",
      "pr_number": 230,
      "action": "closed",
      "title": "Refactor: Extract Toast styles to CSS file",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 20,
      "repo": "electron",
      "pr_number": 229,
      "action": "closed",
      "title": "Refactor SnakeGame styles to external CSS",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 21,
      "repo": "electron",
      "pr_number": 227,
      "action": "closed",
      "title": "feat: fallback to fake data when Gist API fails",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 22,
      "repo": "electron",
      "pr_number": 226,
      "action": "closed",
      "title": "Add error handling test for PollingManager",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 23,
      "repo": "electron",
      "pr_number": 225,
      "action": "closed",
      "title": "Refactor MessageItem to use external CSS file",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 24,
      "repo": "electron",
      "pr_number": 224,
      "action": "closed",
      "title": "Prevent re-introduction of hardcoded Gist token",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 25,
      "repo": "electron",
      "pr_number": 223,
      "action": "closed",
      "title": "Remove unused import in QuestionPreview.tsx",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 26,
      "repo": "electron",
      "pr_number": 222,
      "action": "closed",
      "title": "Remove unused Card import in MultipleChoiceQuestion",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 27,
      "repo": "electron",
      "pr_number": 219,
      "action": "closed",
      "title": "Palette: Clear Search Button",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 28,
      "repo": "electron",
      "pr_number": 218,
      "action": "closed",
      "title": "Sentinel: Add Content Security Policy (CSP)",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 29,
      "repo": "electron",
      "pr_number": 217,
      "action": "closed",
      "title": "Bolt: Add ETag caching to dailySpinService",
      "reason": "conflict",
      "created_at": "2026-03-07 05:41:07"
    },
    {
      "id": 14,
      "repo": "cooperative-apps",
      "pr_number": 46,
      "action": "merged",
      "title": "🎨 Palette: Add aria-labels to dismiss error buttons",
      "reason": "clean_merge",
      "created_at": "2026-03-01 01:19:34"
    },
    {
      "id": 13,
      "repo": "electron",
      "pr_number": 240,
      "action": "closed",
      "title": "🧹 Remove unused Card import from MultipleChoiceQuestion",
      "reason": "conflict",
      "created_at": "2026-03-01 01:19:15"
    },
    {
      "id": 12,
      "repo": "zine-ify",
      "pr_number": 127,
      "action": "merged",
      "title": "🎨 Palette: Keyboard Shortcut Discoverability & Wiring",
      "reason": "clean_merge",
      "created_at": "2026-03-01 01:18:58"
    },
    {
      "id": 11,
      "repo": "cooperative-apps",
      "pr_number": 47,
      "action": "merged",
      "title": "feat: init cooperative stacking application",
      "reason": "clean_merge",
      "created_at": "2026-02-28 00:48:09"
    },
    {
      "id": 7,
      "repo": "Naming-Nosferatu",
      "pr_number": 675,
      "action": "closed",
      "title": "Refactor: Consolidate tournament hooks and fix state restoration bug",
      "reason": "conflict",
      "created_at": "2026-02-27 00:09:31"
    },
    {
      "id": 8,
      "repo": "Naming-Nosferatu",
      "pr_number": 671,
      "action": "closed",
      "title": "🎨 Palette: Improve ScrollToTop button UX",
      "reason": "conflict",
      "created_at": "2026-02-27 00:09:31"
    },
    {
      "id": 9,
      "repo": "Naming-Nosferatu",
      "pr_number": 668,
      "action": "closed",
      "title": "⚡ Bolt: Add caching to analytics endpoints",
      "reason": "conflict",
      "created_at": "2026-02-27 00:09:31"
    },
    {
      "id": 10,
      "repo": "Naming-Nosferatu",
      "pr_number": 665,
      "action": "closed",
      "title": "⚡ Bolt: Add in-memory caching for analytics endpoints",
      "reason": "conflict",
      "created_at": "2026-02-27 00:09:31"
    },
    {
      "id": 5,
      "repo": "zine-ify",
      "pr_number": 124,
      "action": "merged",
      "title": "",
      "reason": "clean_merge",
      "created_at": "2026-02-27 00:09:06"
    },
    {
      "id": 6,
      "repo": "zine-ify",
      "pr_number": 123,
      "action": "closed",
      "title": "",
      "reason": "conflict",
      "created_at": "2026-02-27 00:09:06"
    },
    {
      "id": 4,
      "repo": "electron",
      "pr_number": 216,
      "action": "merged",
      "title": "⚡ Bolt: Optimize Watchlist memory lookup",
      "reason": "clean_merge",
      "created_at": "2026-02-27 00:08:05"
    },
    {
      "id": 3,
      "repo": "cooperative-apps",
      "pr_number": 44,
      "action": "merged",
      "title": "🎨 Palette: Enhance UX with tooltips and input padding",
      "reason": "clean_merge",
      "created_at": "2026-02-27 00:06:22"
    },
    {
      "id": 1,
      "repo": "cooperative-apps",
      "pr_number": 40,
      "action": "merged",
      "title": "⚡ Bolt: Optimize Emoji Drag Performance",
      "reason": "clean_merge",
      "created_at": "2026-02-26 00:18:25"
    },
    {
      "id": 2,
      "repo": "cooperative-apps",
      "pr_number": 39,
      "action": "merged",
      "title": "🎨 Palette: Accessible Auto-Save Status & Tooltips",
      "reason": "clean_merge",
      "created_at": "2026-02-26 00:18:25"
    }
  ],
  "repos": [
    {
      "repo": "cooperative-apps",
      "owner": "guitarbeat",
      "active": 1,
      "default_branch": "main",
      "priority": "critical",
      "notes": "Clean - 0 open PRs, all Jules sessions completed"
    },
    {
      "repo": "electron",
      "owner": "guitarbeat",
      "active": 1,
      "default_branch": "main",
      "priority": "normal",
      "notes": "Clean - 0 open PRs, Jules perf session completed"
    },
    {
      "repo": "Naming-Nosferatu",
      "owner": "guitarbeat",
      "active": 1,
      "default_branch": "main",
      "priority": "normal",
      "notes": "Cleared - 3 merged, 5 conflicts closed"
    },
    {
      "repo": "bledsoe-mobile-notary",
      "owner": "guitarbeat",
      "active": 1,
      "default_branch": "main",
      "priority": "normal",
      "notes": "Cleared - 7 merged, 13 conflicts closed"
    },
    {
      "repo": "zine-ify",
      "owner": "guitarbeat",
      "active": 1,
      "default_branch": "main",
      "priority": "normal",
      "notes": "Cleared - 5 merged, 7 conflicts closed"
    },
    {
      "repo": "actual-mcp",
      "owner": "guitarbeat",
      "active": 1,
      "default_branch": "main",
      "priority": "normal",
      "notes": "Cleared - 1 merged"
    }
  ],
  "sessions": [
    {
      "session_id": "14769626312283604188",
      "repo": "cooperative-apps",
      "focus": "Security hardening: rate limiting, input validation, error handling",
      "status": "DELETED",
      "pr_number": null,
      "created_at": "2026-02-22 10:20:25",
      "updated_at": "2026-04-02 11:36:51"
    },
    {
      "session_id": "103299522730303090",
      "repo": "Year-Grid-Generator",
      "focus": "Accessibility: keyboard shortcuts, hex color input, ARIA labels",
      "status": "DELETED",
      "pr_number": null,
      "created_at": "2026-02-22 10:20:25",
      "updated_at": "2026-04-02 11:36:51"
    },
    {
      "session_id": "2162891879088892659",
      "repo": "electron",
      "focus": "Performance: React.memo, useCallback, virtual scrolling",
      "status": "DELETED",
      "pr_number": null,
      "created_at": "2026-02-22 10:20:25",
      "updated_at": "2026-04-02 11:36:51"
    }
  ],
  "triggerRuns": [
    {
      "run_id": 3,
      "timestamp": "2026-04-10 22:57:06",
      "repos_scanned": 6,
      "prs_processed": 43,
      "errors": "electron #371 + zine-ify #211,#209,#206 mergeable=null, retry next run"
    },
    {
      "run_id": 2,
      "timestamp": "2026-03-31 00:27:31",
      "repos_scanned": 6,
      "prs_processed": 36,
      "errors": "Trigger was missing for 2 days (Mar 18-20). 28 PRs pending mergeable=null computation. Restored trigger cti_vp3z65rnyt0rtfkqa0qh."
    },
    {
      "run_id": 1,
      "timestamp": "2026-03-18 17:03:25",
      "repos_scanned": 6,
      "prs_processed": 40,
      "errors": "4 repos inaccessible; ~30 PRs pending GitHub merge computation"
    }
  ],
  "totalMerged": 40,
  "totalClosed": 181,
  "generatedAt": "2026-05-24T22:27:12.640468Z"
};
